// This file is generated by "./scripts/make_header.sh" and should not be edited manually.
#ifndef NOTATIONKIT_NOTATIONKIT_H
#define NOTATIONKIT_NOTATIONKIT_H

#import <NotationKit/JSON.h>
#import <NotationKit/JSONCore.h>

#endif // NOTATIONKIT_NOTATIONKIT_H
