#!/bin/sh

# Usage:
# ./scripts/make_header.sh

set -e

OUTPUT="Sources/NotationKit.h"

write() {
  printf "%s\n" "$1" >>$OUTPUT
}

writeln() {
  printf "%s\n\n" "$1" >>$OUTPUT
}

printf "" >$OUTPUT
write "// MIT License"
write "//"
write "// Copyright (c) 2022 Notation Kit Project Authors"
write "//"
write "// Permission is hereby granted, free of charge, to any person obtaining a copy"
write "// of this software and associated documentation files (the \"Software\"), to deal"
write "// in the Software without restriction, including without limitation the rights"
write "// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell"
write "// copies of the Software, and to permit persons to whom the Software is"
write "// furnished to do so, subject to the following conditions:"
write "//"
write "// The above copyright notice and this permission notice shall be included in all"
write "// copies or substantial portions of the Software."
write "//"
write "// THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR"
write "// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,"
write "// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE"
write "// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER"
write "// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,"
write "// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE"
writeln "// SOFTWARE."

write "// This file is generated by \"./scripts/make_header.sh\" and should not be edited manually."
write "#ifndef NOTATIONKIT_NOTATIONKIT_H"
writeln "#define NOTATIONKIT_NOTATIONKIT_H"

find Sources -name "*.h" ! -name "NotationKit.h" ! -name "simdjson.h" -exec basename {} \; |
  sort -f | xargs printf "#import <NotationKit/%s>\n" >>$OUTPUT

printf "\n#endif // NOTATIONKIT_NOTATIONKIT_H\n" >>$OUTPUT
echo "Done."
