#!/bin/sh

# Usage:
# ./scripts/make_header.sh

set -e

OUTPUT="Sources/NotationKit.h"

{
  printf "// This file is generated by \"./scripts/make_header.sh\" and should not be edited manually.\n"
  printf "#ifndef NOTATIONKIT_NOTATIONKIT_H\n"
  printf "#define NOTATIONKIT_NOTATIONKIT_H\n\n"

  find Sources/JSONCore Sources/JSONSimd -name "*.h" ! -name "NotationKit.h" ! -name "simdjson.h" -exec basename {} \; |
    sort -f | xargs printf "#import <NotationKit/%s>\n"

  printf "\n#endif // NOTATIONKIT_NOTATIONKIT_H\n"
}>$OUTPUT

echo "Done."
